# Generated by Django 5.0.2 on 2025-05-14 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx'])], verbose_name='Invoice file'),
        ),
    ]
