# Generated by Django 5.0.2 on 2025-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0005_order_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total cost'),
            preserve_default=False,
        ),
    ]
